services:
  user-service:
    build: ../services/user-service
    environment:
      - SERVICE_NAME=user-service
    ports:
      - "8001:8000"

  payments-service:
    build: ../services/payments-service
    environment:
      - SERVICE_NAME=payments-service
    ports:
      - "8002:8000"

  notifications-service:
    build: ../services/notifications-service
    environment:
      - SERVICE_NAME=notifications-service
    ports:
      - "8003:8000"

  api-gateway:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - payments-service
      - notifications-service

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
